FROM chaowen/tensorflow:2.1.0-armv7

WORKDIR /dnn

COPY requirement.txt /dnn/

#RUN pip install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl

RUN apt-get update && apt-get install gcc python3-dev -y && rm -rf /var/lib/apt/lists/*

RUN pip3 install -r requirement.txt

COPY . ./

#RUN cp /usr/bin/python3 /usr/bin/python

CMD ["python", "run.py", "vgg16", "0", "0", "--is-last"]
