FROM chaowen/tensorflow:2.1.0-armv7

WORKDIR /dnn

COPY requirement.txt /dnn/

RUN apt-get update && apt-get install -y python3-pip python3-setuptools python3-psutil python3-bottle python3-requests

RUN pip3 install -r requirement.txt

COPY . ./

CMD ["python", "run.py", "vgg16", "0", "0" "--is-last"]
