FROM chaowen/tensorflow:2.1.0-armv7

WORKDIR /dnn

COPY requirement.txt /dnn/

#RUN pip install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl

RUN pip install -r requirement.txt

COPY . ./

CMD ["python", "run.py", "vgg16", "0", "0" "--is-last"]
